# Generated by Django 4.1.5 on 2023-01-27 01:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.IntegerField(choices=[(0, 'Hembra'), (1, 'Macho')])),
                ('nombre', models.CharField(max_length=50)),
                ('raza', models.CharField(default='Mestizo/criollo', max_length=50)),
                ('edad', models.CharField(max_length=10)),
                ('tamaño', models.CharField(max_length=10)),
                ('adoptado', models.BooleanField(default=False)),
                ('imagen', models.ImageField(upload_to='mascotas/imagenes')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Mascotas',
            },
        ),
    ]
