# Generated by Django 4.1.5 on 2023-01-27 22:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adoptante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='mascota',
            name='edad',
            field=models.IntegerField(choices=[(0, 'Cachorro'), (1, 'Joven'), (2, 'Adulto')]),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tamaño',
            field=models.IntegerField(choices=[(0, 'Pequeño'), (1, 'Mediano'), (2, 'Grande')]),
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('aprobada', models.BooleanField(default=False)),
                ('fecha_aprobacion', models.DateTimeField(null=True)),
                ('adoptante_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.adoptante')),
                ('mascota_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mascotas.mascota')),
            ],
        ),
    ]
